package kr.pe.withwind.nims.domain;

public class ProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PRODUCT_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String productCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PRODUCT_MST_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String productMstCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.NRCD_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String nrcdSeNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PRODUCT_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String productNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PRTM_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String prtmSeNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.MIN_QTY
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String minQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.MIN_QTY_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String minQtyNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PCE_CNT
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String pceCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP.PRODUCT_INFO.PCE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    private String pceNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PRODUCT_CD
     *
     * @return the value of APP.PRODUCT_INFO.PRODUCT_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PRODUCT_CD
     *
     * @param productCd the value for APP.PRODUCT_INFO.PRODUCT_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PRODUCT_MST_CD
     *
     * @return the value of APP.PRODUCT_INFO.PRODUCT_MST_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getProductMstCd() {
        return productMstCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PRODUCT_MST_CD
     *
     * @param productMstCd the value for APP.PRODUCT_INFO.PRODUCT_MST_CD
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setProductMstCd(String productMstCd) {
        this.productMstCd = productMstCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.NRCD_SE_NM
     *
     * @return the value of APP.PRODUCT_INFO.NRCD_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getNrcdSeNm() {
        return nrcdSeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.NRCD_SE_NM
     *
     * @param nrcdSeNm the value for APP.PRODUCT_INFO.NRCD_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setNrcdSeNm(String nrcdSeNm) {
        this.nrcdSeNm = nrcdSeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PRODUCT_NM
     *
     * @return the value of APP.PRODUCT_INFO.PRODUCT_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getProductNm() {
        return productNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PRODUCT_NM
     *
     * @param productNm the value for APP.PRODUCT_INFO.PRODUCT_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setProductNm(String productNm) {
        this.productNm = productNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PRTM_SE_NM
     *
     * @return the value of APP.PRODUCT_INFO.PRTM_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getPrtmSeNm() {
        return prtmSeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PRTM_SE_NM
     *
     * @param prtmSeNm the value for APP.PRODUCT_INFO.PRTM_SE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setPrtmSeNm(String prtmSeNm) {
        this.prtmSeNm = prtmSeNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.MIN_QTY
     *
     * @return the value of APP.PRODUCT_INFO.MIN_QTY
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getMinQty() {
        return minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.MIN_QTY
     *
     * @param minQty the value for APP.PRODUCT_INFO.MIN_QTY
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setMinQty(String minQty) {
        this.minQty = minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.MIN_QTY_NM
     *
     * @return the value of APP.PRODUCT_INFO.MIN_QTY_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getMinQtyNm() {
        return minQtyNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.MIN_QTY_NM
     *
     * @param minQtyNm the value for APP.PRODUCT_INFO.MIN_QTY_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setMinQtyNm(String minQtyNm) {
        this.minQtyNm = minQtyNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PCE_CNT
     *
     * @return the value of APP.PRODUCT_INFO.PCE_CNT
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getPceCnt() {
        return pceCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PCE_CNT
     *
     * @param pceCnt the value for APP.PRODUCT_INFO.PCE_CNT
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setPceCnt(String pceCnt) {
        this.pceCnt = pceCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.PRODUCT_INFO.PCE_NM
     *
     * @return the value of APP.PRODUCT_INFO.PCE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public String getPceNm() {
        return pceNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.PRODUCT_INFO.PCE_NM
     *
     * @param pceNm the value for APP.PRODUCT_INFO.PCE_NM
     *
     * @mbg.generated Tue Apr 10 13:54:55 KST 2018
     */
    public void setPceNm(String pceNm) {
        this.pceNm = pceNm;
    }
}