select * from sys.sysschemas;
select * from sys.systables;
select * from sys.syscolumns;
--- 소유중인 테이블 목록보기
select a.* from sys.systables a, sys.sysschemas b
where 1=1
and b.schemaname = 'APP'
and a.schemaid = b.schemaid
;
-- 특정 테이블의 컬럼 정보 보기
select 
    a.tablename
    ,c.columnname
    ,c.columndatatype
    ,c.columndefault
from sys.systables a, sys.sysschemas b, sys.syscolumns c
where 1=1
and b.schemaname = 'APP'
and a.tablename = 'BSSH_INFO'
and a.schemaid = b.schemaid
and c.referenceid = a.tableid
order by c.columnnumber
;

CREATE TABLE BSSH_SETTING
(
    INF_TYPE VARCHAR(10) NOT NULL,
    BSSH_CD VARCHAR(20),
    AUTH_KEY VARCHAR(200),
    RPTR_NM VARCHAR(50),
    RPTR_ENTRPS_NM VARCHAR(200),
    PUBLIC_KEY VARCHAR(1000) NOT NULL DEFAULT '30820122300d06092a864886f70d01010105000382010f003082010a0282010100a276b723301526dcec143d1d8c77ba2c007dddf14b461d403c9db5fce2ca7091cbecf0622af3aebcb7d7e824dbeb33c281906815c829df82ff8a5c5224336fd4038d3c2bef7b28b21c00f81c087813d0b28298aa67cc63cb8f3e3d7265533380e5f649082f14bfcb6439bf8530275be3cdb3c7cb2ee535e2f8e73ef693bf0bedcb40726bd908c9816c0ed9b03a5f7c1770998db39cb292c7c6c09eb81033c1d4d1193ceb1571d5c41bd9388f697621169baba50648cb9c4a9bd9f8eac168dcba8337923b712824eaa4951bef19f726ca7f5e87d8dde3de7ff2e42001544ca7b55a83ab0ecc0c483c79a97666b0be513d4e619a97330668ec725776973b55421b0203010001',
    CHRG_NM VARCHAR(50),
    CHRG_TEL_NO VARCHAR(50),
    CHRG_MP_NO VARCHAR(50),
    REGISTER_ID VARCHAR(50),
    PRIMARY KEY(INF_TYPE)
)
;

insert into bssh_setting 
select * from bssh_info;


select * From BSSH_INFO;

ALTER TABLE RPT_LIST
ADD COLUMN REG_DT timestamp default current_timestamp NOT NULL; 

CREATE TABLE DISS_CODE
(
    DISS_SEQ CHAR(16) NOT NULL
    ,KCD_REFORM_ODR CHAR(1)
    ,DISS_CD VARCHAR(10)
    ,UPPER_DISS_CD VARCHAR(10)
    ,DISS_NM VARCHAR(500)
    ,DISS_NM_EN VARCHAR(500)
    ,REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,PRIMARY KEY (DISS_SEQ)
);

SELECT 
    DISS_SEQ
    ,KCD_REFORM_ODR
    ,DISS_CD
    ,UPPER_DISS_CD
    ,DISS_NM
    ,DISS_NM_EN
    ,REG_DT
FROM DISS_CODE
WHERE 1=1

ORDER BY DISS_CD, UPPER_DISS_CD;



select current_timestamp from SYSIBM.SYSDUMMY1;


CREATE TABLE RPT_ERR_INFO
(
    BSSH_CD VARCHAR(15) NOT NULL,
    USR_RPT_ID_NO VARCHAR(50) NOT NULL,
    IDX SMALLINT,
    ERROR_CD VARCHAR(10),
    ERROR_MSG VARCHAR(2000),
    PRIMARY KEY (BSSH_CD, USR_RPT_ID_NO, IDX)
);


select 
RL.BSSH_CD
,RL.USR_RPT_ID_NO
,RL.RESULT_CD
,RL.RESULT_MSG
,RL.RPT_RCEPT_NO
,RL.RPT_FILE_NAME
,RL.RPT_SE_CD
,RL.REG_DT
,RL.RPT_TY_CD
,RL.STATUS
,COALESCE (T2.CODE_NM,'��') AS STATUS_NM
,COALESCE (T1.CODE_NM,'��') AS RPT_TY_CD_NM
,COALESCE (T3.CODE_NM,'��') AS RPT_SE_CD_NM
FROM RPT_LIST AS RL
LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_TY_CD') AS T1 ON RL.RPT_TY_CD = T1.CODE
LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_STATUS') AS T2 ON RL.STATUS = T2.CODE
LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_TYPE') AS T3 ON RL.RPT_SE_CD = T3.CODE
ORDER BY RL.REG_DT DESC;

SELECT * FROM SYS_CODE;

ALTER TABLE RPT_LIST
ALTER COLUMN RPT_TY_CD DEFAULT '0';

UPDATE RPT_LIST SET RPT_TY_CD = '0';

SELECT * FROM RPT_ERR_INFO;


TSTNIMSW1	SLM1526462536488	1	����	SLM	9999	���� ���� �Ǿ����ϴ�.	20180516_20629800	C:\�����׽�Ʈ\TSTNIMSW1SLM20180516182217_0001.xml	2018-05-16 18:22:17.92

UPDATE RPT_LIST SET STATUS='0';

UPDATE RPT_LIST SET RPT_TY_CD='0' WHERE BSSH_CD='TSTNIMSW1' AND USR_RPT_ID_NO='SLM1526462536488';


select * from XLS_MAPPING;



select * from stock_info;

select * from sys_code where code='STOCK_LIST';
SELECT * FROM SYS_CODE WHERE P_CODE='STOCK_LIST';

UPDATE SYS_CODE SET CODE='STOCK_INFO' WHERE CODE='STOCK_LIST';

alter table bssh_info
ADD COLUMN REGISTER_ID varchar(50);


SELECT * FROM PRODUCT_INFO;

SELECT 
    A.STORAGE_NO
    ,A.PRODUCT_CD
    ,B.PRODUCT_NM || '['|| B.MIN_QTY || B.MIN_QTY_NM || ' ' || B.PCE_CNT || B.PCE_NM ||']' AS PRODUCT_NM
    ,A.LOT_NO
    ,A.VALID_DE
    ,A.SERIAL_NO
    ,A.BARCODE_STR
    ,A.PIECE_CNT
    ,A.REASON_CD
    ,A.USR_RPT_ID_NO
    ,A.REG_DT
    ,A.MOD_DT
FROM STOCK_INFO A LEFT JOIN PRODUCT_INFO B ON A.PRODUCT_CD = B.PRODUCT_CD
WHERE 1=1
ORDER BY PRODUCT_CD, VALID_DE DESC;


CREATE SEQUENCE PATNT_INFO_SEQ
AS BIGINT
START WITH 1000000000;

CREATE TABLE PATNT_INFO
(
    PATNT_NO BIGINT NOT NULL
    ,PATNT_NM VARCHAR(60) NOT NULL
    ,ID_TYPE VARCHAR(5)
    ,ID_NO VARCHAR(128)
    ,BRTHDY VARCHAR(8)
    ,SEX CHAR(1)
    ,DEL_YN CHAR(1) DEFAULT 'N' NOT NULL
    ,TEL_NO VARCHAR(20)
    ,ADDR VARCHAR(200)
    ,ETC VARCHAR(1000)
    ,REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,PRIMARY KEY(PATNT_NO)
);

values current_timestamp;
VALUES ('P' || CAST(NEXT VALUE FOR PATNT_INFO_SEQ AS VARCHAR()));

select * from Patnt_Info;

CREATE TABLE INCOM_BY_PURCHASE
(
    BSSH_CD VARCHAR(15) NOT NULL
    ,USR_RPT_ID_NO VARCHAR(50) NOT NULL
    ,STD_DE VARCHAR(8) NOT NULL
    ,REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,PRIMARY KEY(BSSH_CD, USR_RPT_ID_NO)
);

select * from INCOM_BY_PURCHASE;

select * from Product_Info;
delete from product_info;

select * from RPT_LIST
where 
BSSH_CD = 'TSTNIMSW1'
AND USR_RPT_ID_NO = 'PCM1528119184621';

update RPT_LIST set
    RPT_SE_CD = 'PCM'
where 
BSSH_CD = 'TSTNIMSW1'
AND USR_RPT_ID_NO = 'PCM1528172139688';
             
             
SELECT 
			RL.BSSH_CD
			,RL.USR_RPT_ID_NO
			,RL.RESULT_CD
			,RL.RESULT_MSG
			,RL.RPT_RCEPT_NO
			,RL.RPT_FILE_NAME
			,RL.RPT_SE_CD
			,RL.REG_DT
			,RL.RPT_TY_CD
			,RL.STATUS
			,COALESCE (T2.CODE_NM,'��') AS STATUS_NM
			,COALESCE (T1.CODE_NM,'��') AS RPT_TY_CD_NM
			,COALESCE (T3.CODE_NM,'��') AS RPT_SE_CD_NM
		FROM RPT_LIST AS RL
			LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_TY_CD') AS T1 ON RL.RPT_TY_CD = T1.CODE
			LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_STATUS') AS T2 ON RL.STATUS = T2.CODE
			LEFT OUTER JOIN (SELECT CODE, CODE_NM FROM SYS_CODE WHERE P_CODE='RPT_TYPE') AS T3 ON RL.RPT_SE_CD = T3.CODE
		WHERE 1=1
        
order by reg_dt desc;